# {"version": "2.4.0", "desc": "tail sampling opentelemetry input"}
[[inputs.opentelemetry]]
  customer_tags = ["body_code", "trace_keep", "test_case", "expected_rule", "run_id"]
  customer_tags_all = false
  keep_rare_resource = false
  del_message = false
  clean_message = true
  split_service_name = true

  [inputs.opentelemetry.sampler]
    sampling_rate = 1.0

  [inputs.opentelemetry.http]
    enable = true
    http_status_ok = 200
    trace_api = "/otel/v1/traces"
    metric_api = "/otel/v1/metrics"
    logs_api = "/otel/v1/logs"

  [inputs.opentelemetry.grpc]
    trace_enable = true
    metric_enable = true
    addr = "0.0.0.0:4317"
    max_payload = 16777216
